# Custom Language File for Launcher Customizer

[ejs.app]
title = "Elysium Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/DevZunxBR/Elysium-Launcher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/hshhzHgXJU"

[ejs.settings]
sourceGithubLink = "https://github.com/DevZunxBR/Elysium-Launcher"
supportLink = "https://github.com/DevZunxBR/Elysium-Launcher/issues"

[ejs.welcome]
welcomeHeader = "ELYSIUM LAUNCHER (BETA)"
welcomeDescription = "O Elysium Launcher é uma plataforma gratuita desenvolvida para você baixar e jogar Minecraft sem complicações. O aplicativo atualmente encontra-se em fase BETA, o que significa que estamos trabalhando em melhorias constantes e correções de desempenho."
welcomeDescCTA = "Faça seu login abaixo para baixar e começar a jogar."
